[build]
  command = "npm install; bundle install; cd website; JEKYLL_ENV=production bundle exec jekyll build --config config/jekyll.config.yml;"
  publish = "website/build"

[context.development]
  command = "npm install; bundle install; cd website; bundle exec jekyll build --config config/jekyll.config.yml, config/jekyll.config.dev.yml"
  publish = "website/build"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"